import { EventStatus } from './event-status.model';
import { SocialLinks } from './user.model';

export interface Event {
  id: string;
  title: string;
  description: string;
  additionalInfo?: string;
  socialLinks?: SocialLinks;
  imageUrl: string;
  // An event can be more than one type (e.g. workshop then jam) and more
  // than one dance style (e.g. Swing and Rock&Roll) - at least one of each
  // is enforced where these are edited (event-detail.page.ts's editValid).
  typeIds: string[];
  disciplineIds: string[];
  eventDateFrom: number;
  eventDateTo: number;
  status: EventStatus;
  isFree: boolean;
  price: number;
  creatorId: string;
  address: string;
  city: string;
  latitude: number;
  longitude: number;
  /** Set together on every instance generated by a recurring-event series
   * (see EventService.createSeries) - undefined for a plain one-off event. */
  seriesId?: string;
  seriesIndex?: number;
  seriesTotal?: number;
  createdAt: number;
  updatedAt?: number;
}

export type EventRelation = 'creator' | 'favorite';

export type PriceOption = 'free' | 'paid';

export type RelationOption = 'organizer' | 'attendee';

/** An event hydrated with just its creator's name - the common shape shared
 * by every list that renders <app-event-card> without a lookup per event. */
export interface EventWithCreatorName extends Event {
  creatorName: string;
}

/** An event returned by the Favorites list - additionally tagged with how
 * the current user relates to it (organizes it, favorited it, or both). */
export interface FavoritedEvent extends EventWithCreatorName {
  relation: EventRelation;
}

/** One row of an event's attendee list - same shape as FollowUser (one row
 * of a followers/following list), just "since" the user marked themselves
 * attending this event instead of since they followed someone. */
export interface Attendee {
  id: string;
  name: string;
  photoUrl?: string;
  disciplineIds: string[];
  attendedAt: number;
}

export interface EventSearchParams {
  disciplineIds?: string[];
  typeIds?: string[];
  statuses?: EventStatus[];
  dateFrom?: number;
  dateTo?: number;
  latitude?: number;
  longitude?: number;
  radius?: number;
  search?: string;
  priceOptions?: PriceOption[];
}

/** Partial update sent to PUT /api/events/:id - any subset of editable event fields. */
export type UpdateEventPayload = Partial<Omit<Event, 'id' | 'creatorId' | 'createdAt' | 'updatedAt'>>;

/** Payload sent to POST /api/events - every field CreateEventDto requires. */
export type CreateEventPayload = Omit<Event, 'id' | 'createdAt' | 'updatedAt'>;

export type RecurrenceFrequency = 'weekly' | 'monthlyNthWeekday';

/** e.g. { nth: 2, weekday: 5 } = the 2nd Saturday of the month (0=Monday..6=Sunday). */
export interface NthWeekday {
  nth: number;
  weekday: number;
}

export interface RecurrenceRule {
  frequency: RecurrenceFrequency;
  /** Every N weeks (frequency='weekly') or every N months (frequency='monthlyNthWeekday'). */
  interval: number;
  /** 0-6 (Monday-first), required when frequency='weekly'. */
  weekdays?: number[];
  /** Required when frequency='monthlyNthWeekday'. */
  nthWeekdays?: NthWeekday[];
  dateFrom: number;
  /** null = "sin límite" - the backend caps generation at a safety maximum instead of a concrete end date. */
  dateTo: number | null;
}

/** Payload sent to POST /api/events/series - every CreateEventPayload field
 * except the per-instance dates/status, plus the rule used to generate them
 * and the single time-of-day range applied to every occurrence. */
export interface CreateEventSeriesPayload extends Omit<CreateEventPayload, 'eventDateFrom' | 'eventDateTo' | 'status'> {
  recurrence: RecurrenceRule;
  /** "HH:mm", applied to every generated occurrence. */
  timeFrom: string;
  timeTo: string;
}

/** Payload sent to PATCH /api/events/series/:seriesId - bulk-edits every
 * instance of a series at once. No absolute date fields (each instance
 * keeps its own date); timeFrom/timeTo (given together) shift every
 * instance's time-of-day while preserving its date and duration. */
export type PatchEventSeriesPayload = Partial<
  Omit<Event, 'id' | 'creatorId' | 'createdAt' | 'updatedAt' | 'eventDateFrom' | 'eventDateTo' | 'seriesId' | 'seriesIndex' | 'seriesTotal'>
> & {
  timeFrom?: string;
  timeTo?: string;
};
